import type { Metadata } from 'next';
import { Work_Sans } from 'next/font/google';
import '@styles/reset.css';
import '@styles/globalStyles.scss';
import '@styles/colors.css';
import Header from '@components/Header/Header';
import Footer from '@components/Footer/Footer';
import Body from '@components/Layouts/Body';
import StoreProvider from '@components/Layouts/StoreProvider';

const workSans = Work_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <Body font={`${workSans.className}`}>
          <div className="wrapper">
            <Header />
            <main className="main">{children}</main>
            <Footer />
          </div>
        </Body>
      </html>
    </StoreProvider>
  );
}
